apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
  namespace: urban-data

data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_TOPIC: "urban_sensors"
  SPARK_APP_NAME: "urban-sensors-streaming"